/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import edd.ColasCircularesDinamicas;
import edd.LDLC;
import edd.Manipulacion;
import edd.Nodo;
import edd.NodoL;
import edd.Prioridad;
import edd.Proceso;
import poo.Archivos;

/**
 *
 * @author osval
 */
public class BajasDeProcesos extends javax.swing.JFrame
{

    /**
     * Creates new form BajasDeProcesos
     */
    public BajasDeProcesos()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        bajaProcesos = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        ingresePrioridad = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        panelProceso = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        númeroDePropiedad = new javax.swing.JLabel();
        quantums = new javax.swing.JLabel();
        textoNumPrioridad = new javax.swing.JTextField();
        textoQuan = new javax.swing.JTextField();
        textoNom = new javax.swing.JTextField();
        botonLimpiarCampos = new javax.swing.JButton();
        botonBorrarProceso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(48, 146, 255));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SímboloCerrar.png"))); // NOI18N
        botonSalir.setToolTipText("Cerrar programa");
        botonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonSalirActionPerformed(evt);
            }
        });

        bajaProcesos.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        bajaProcesos.setText("Bajas de procesos");

        textoNombre.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        textoNombre.setToolTipText("Insertar el nombre del proceso a borrar");
        textoNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textoNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textoNombreActionPerformed(evt);
            }
        });
        textoNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                textoNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoNombreKeyTyped(evt);
            }
        });

        ingresePrioridad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ingresePrioridad.setText("Nombre del proceso:");

        botonAceptar.setBackground(new java.awt.Color(102, 255, 102));
        botonAceptar.setText("Aceptar");
        botonAceptar.setToolTipText("Buscar proceso");
        botonAceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonAceptarActionPerformed(evt);
            }
        });
        botonAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                botonAceptarKeyPressed(evt);
            }
        });

        botonRegresar.setBackground(new java.awt.Color(255, 255, 0));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        botonRegresar.setToolTipText("Menú Principal");
        botonRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonRegresarActionPerformed(evt);
            }
        });

        panelProceso.setBackground(new java.awt.Color(102, 255, 102));
        panelProceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        nombre.setText("Nombre:");

        númeroDePropiedad.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        númeroDePropiedad.setText("Número de Prioridad:");

        quantums.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        quantums.setText("Quantums:");

        textoNumPrioridad.setEditable(false);
        textoNumPrioridad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNumPrioridad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textoNumPrioridad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoNumPrioridadKeyTyped(evt);
            }
        });

        textoQuan.setEditable(false);
        textoQuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoQuan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textoNom.setEditable(false);
        textoNom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelProcesoLayout = new javax.swing.GroupLayout(panelProceso);
        panelProceso.setLayout(panelProcesoLayout);
        panelProcesoLayout.setHorizontalGroup(
            panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcesoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProcesoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(quantums)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoQuan))
                    .addGroup(panelProcesoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNom))
                    .addGroup(panelProcesoLayout.createSequentialGroup()
                        .addComponent(númeroDePropiedad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNumPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        panelProcesoLayout.setVerticalGroup(
            panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcesoLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(númeroDePropiedad)
                    .addComponent(textoNumPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(textoNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantums))
                .addGap(51, 51, 51))
        );

        botonLimpiarCampos.setBackground(new java.awt.Color(255, 255, 0));
        botonLimpiarCampos.setText("Limpiar");
        botonLimpiarCampos.setToolTipText("Limpiar los campos");
        botonLimpiarCampos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonLimpiarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLimpiarCampos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonLimpiarCamposActionPerformed(evt);
            }
        });

        botonBorrarProceso.setBackground(new java.awt.Color(255, 0, 0));
        botonBorrarProceso.setText("Borrar");
        botonBorrarProceso.setToolTipText("Borrar Proceso");
        botonBorrarProceso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonBorrarProceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrarProceso.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonBorrarProcesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(ingresePrioridad)
                                .addGap(18, 18, 18)
                                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(botonLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonBorrarProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(bajaProcesos)
                                .addGap(162, 162, 162))
                            .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(panelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bajaProcesos)
                .addGap(40, 40, 40)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresePrioridad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrarProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSalirActionPerformed
    {//GEN-HEADEREND:event_botonSalirActionPerformed
        Archivos.guarda(this, MenuPrincipal.lista, "Datos.dat");
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textoNombreActionPerformed
    {//GEN-HEADEREND:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoNombreKeyTyped
    {//GEN-HEADEREND:event_textoNombreKeyTyped
        Validaciones.validaAlfabeticos(evt, 15, textoNombre.getText());
    }//GEN-LAST:event_textoNombreKeyTyped

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed
        try
        {
        if (MenuPrincipal.lista.getR() != null)
        {
            boolean b = Manipulacion.verificaNombreProceso(MenuPrincipal.lista, textoNombre.getText());

            if (b != false)
            {
                NodoL aux = MenuPrincipal.lista.getR();
                Nodo aux3;
                do
                {
                    aux = aux.getSiguiente();
                    ColasCircularesDinamicas cola = new ColasCircularesDinamicas();
                    do
                    {
                        aux3 = ((Prioridad) aux.getObj()).getCola().elimina();
                        if (aux3.getEtiqueta().equals(textoNombre.getText()))
                        {
                            textoNumPrioridad.setText(String.valueOf(((Prioridad) aux.getObj()).getNoPrioridad()));
                            textoNom.setText(((Proceso) aux3.getObj()).getNombre());
                            textoQuan.setText(String.valueOf(((Proceso) aux3.getObj()).getQuantums()));
                        }
                        cola.inserta(aux3);
                    } while (((Prioridad) aux.getObj()).getCola().getAtras() != null);
                    ((Prioridad) aux.getObj()).setCola(cola);
                } while (aux != MenuPrincipal.lista.getR());
            } else
            {
                Mensajes.error(this, "No se encontró el proceso.");
            }
            CtrlInterfaz.limpia(textoNombre);
        } else
        {
            Mensajes.error(this, "Error. Lista vacía.");
            new MenuPrincipal().setVisible(true);
            dispose();
        }
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRegresarActionPerformed
    {//GEN-HEADEREND:event_botonRegresarActionPerformed
        Archivos.guarda(this, MenuPrincipal.lista, "Datos.dat");
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        MenuPrincipal.lista = (LDLC) Archivos.carga(this, "Datos.dat");

        if (MenuPrincipal.lista == null || MenuPrincipal.lista.getR() == null)
        {
            Mensajes.error(this, "No hay datos para mostrar. Lista vacía.");
            new MenuPrincipal().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void textoNumPrioridadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoNumPrioridadKeyTyped
    {//GEN-HEADEREND:event_textoNumPrioridadKeyTyped

    }//GEN-LAST:event_textoNumPrioridadKeyTyped

    private void botonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonLimpiarCamposActionPerformed
    {//GEN-HEADEREND:event_botonLimpiarCamposActionPerformed
        CtrlInterfaz.limpia(textoNom, textoNombre, textoNumPrioridad, textoQuan);
        CtrlInterfaz.cambia(textoNombre);
    }//GEN-LAST:event_botonLimpiarCamposActionPerformed

    private void botonBorrarProcesoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBorrarProcesoActionPerformed
    {//GEN-HEADEREND:event_botonBorrarProcesoActionPerformed
        try
        {
            MenuPrincipal.lista = (LDLC) Archivos.carga(this, "Datos.dat");

            if (textoNombre.getText() == null)
            {
                Mensajes.error(this, "Error, no ha ingresado un proceso para borrar.");
                CtrlInterfaz.limpia(textoNombre);
                CtrlInterfaz.cambia(textoNombre);
            } else
            {
                MenuPrincipal.lista = Manipulacion.bajaProceso(MenuPrincipal.lista, textoNom.getText());
                Mensajes.exito(this, "Se borró el proceso con éxito");
                Archivos.guarda(this, MenuPrincipal.lista, "Datos.dat");
                CtrlInterfaz.limpia(textoNom, textoNombre, textoNumPrioridad, textoQuan);
                CtrlInterfaz.cambia(textoNombre);
                if (MenuPrincipal.lista.getR() == null)
                {
                    Mensajes.error(this, "Lista vacía.");
                    new MenuPrincipal().setVisible(true);
                    dispose();
                }
                
            }
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
        }
    }//GEN-LAST:event_botonBorrarProcesoActionPerformed

    private void textoNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoNombreKeyPressed
    {//GEN-HEADEREND:event_textoNombreKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, textoNombre, botonAceptar);
    }//GEN-LAST:event_textoNombreKeyPressed

    private void botonAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_botonAceptarKeyPressed
    {//GEN-HEADEREND:event_botonAceptarKeyPressed
        try
        {
            if (MenuPrincipal.lista.getR() != null)
            {
                boolean b = Manipulacion.verificaNombreProceso(MenuPrincipal.lista, textoNombre.getText());
                if (b != false)
                {
                    NodoL aux = MenuPrincipal.lista.getR();
                    Nodo aux3;
                    do
                    {
                        aux = aux.getSiguiente();
                        ColasCircularesDinamicas cola = new ColasCircularesDinamicas();
                        do
                        {
                            aux3 = ((Prioridad) aux.getObj()).getCola().elimina();
                            if (aux3.getEtiqueta().equals(textoNombre.getText()))
                            {
                                textoNumPrioridad.setText(String.valueOf(((Prioridad) aux.getObj()).getNoPrioridad()));
                                textoNom.setText(((Proceso) aux3.getObj()).getNombre());
                                textoQuan.setText(String.valueOf(((Proceso) aux3.getObj()).getQuantums()));
                            }
                            cola.inserta(aux3);
                        } while (((Prioridad) aux.getObj()).getCola().getAtras() != null);
                        ((Prioridad) aux.getObj()).setCola(cola);
                    } while (aux != MenuPrincipal.lista.getR());
                } else
                {
                    Mensajes.error(this, "No se encontró el proceso.");
                }
                CtrlInterfaz.limpia(textoNombre);
            } else
            {
                Mensajes.error(this, "Error. Lista vacía.");
                new MenuPrincipal().setVisible(true);
                dispose();
            }
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
        }
    }//GEN-LAST:event_botonAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BajasDeProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BajasDeProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BajasDeProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BajasDeProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BajasDeProcesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bajaProcesos;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBorrarProceso;
    private javax.swing.JButton botonLimpiarCampos;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel ingresePrioridad;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel númeroDePropiedad;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelProceso;
    private javax.swing.JLabel quantums;
    private javax.swing.JTextField textoNom;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoNumPrioridad;
    private javax.swing.JTextField textoQuan;
    // End of variables declaration//GEN-END:variables
}
