/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import edd.ColasCircularesDinamicas;
import edd.LDLC;
import edd.Nodo;
import edd.NodoL;
import edd.Prioridad;
import edd.Proceso;
import javax.swing.JComboBox;
import poo.Archivos;

/**
 *
 * @author osval
 */
public class ConsultasProcesos extends javax.swing.JFrame
{

    public static NodoL aux = null;
    public static Nodo aux3 = null;

    /**
     * Creates new form ConsultasProcesos
     */
    public ConsultasProcesos()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel = new javax.swing.JPanel();
        botonRegresar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        ingresePrioridad = new javax.swing.JLabel();
        textoPrio = new javax.swing.JTextField();
        botonAcep = new javax.swing.JButton();
        prioridad = new javax.swing.JLabel();
        priori = new javax.swing.JTextField();
        panelProceso = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        númeroDePropiedad = new javax.swing.JLabel();
        quantums = new javax.swing.JLabel();
        textoNumPrioridad = new javax.swing.JTextField();
        textoQuan = new javax.swing.JTextField();
        textoNom = new javax.swing.JTextField();
        botonAnterior = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        panel.setBackground(new java.awt.Color(48, 146, 255));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        botonRegresar.setBackground(new java.awt.Color(255, 255, 0));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        botonRegresar.setToolTipText("Menú Principal");
        botonRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonRegresarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SímboloCerrar.png"))); // NOI18N
        botonSalir.setToolTipText("Cerrar programa");
        botonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonSalirActionPerformed(evt);
            }
        });

        ingresePrioridad.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        ingresePrioridad.setText("Ingrese la prioridad:");

        textoPrio.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        textoPrio.setToolTipText("Insertar el nombre del proceso a borrar");
        textoPrio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textoPrio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textoPrioActionPerformed(evt);
            }
        });
        textoPrio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                textoPrioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoPrioKeyTyped(evt);
            }
        });

        botonAcep.setBackground(new java.awt.Color(102, 255, 102));
        botonAcep.setText("Aceptar");
        botonAcep.setToolTipText("Mostrar procesos de la prioridad");
        botonAcep.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonAcep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAcep.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonAcepActionPerformed(evt);
            }
        });
        botonAcep.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                botonAcepKeyPressed(evt);
            }
        });

        prioridad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prioridad.setText("Prioridad:");

        priori.setEditable(false);
        priori.setBackground(new java.awt.Color(153, 204, 255));
        priori.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        priori.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priori.setToolTipText("Prioridad ingresada");
        priori.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelProceso.setBackground(new java.awt.Color(102, 255, 102));
        panelProceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        nombre.setText("Nombre:");

        númeroDePropiedad.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        númeroDePropiedad.setText("Número de Prioridad:");

        quantums.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        quantums.setText("Quantums:");

        textoNumPrioridad.setEditable(false);
        textoNumPrioridad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNumPrioridad.setToolTipText("Número de prioridad del proceso");
        textoNumPrioridad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textoNumPrioridad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoNumPrioridadKeyTyped(evt);
            }
        });

        textoQuan.setEditable(false);
        textoQuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoQuan.setToolTipText("Quantums del proceso");
        textoQuan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textoNom.setEditable(false);
        textoNom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNom.setToolTipText("Nombre del proceso");
        textoNom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelProcesoLayout = new javax.swing.GroupLayout(panelProceso);
        panelProceso.setLayout(panelProcesoLayout);
        panelProcesoLayout.setHorizontalGroup(
            panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcesoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProcesoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(quantums)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoQuan))
                    .addGroup(panelProcesoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNom))
                    .addGroup(panelProcesoLayout.createSequentialGroup()
                        .addComponent(númeroDePropiedad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNumPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        panelProcesoLayout.setVerticalGroup(
            panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProcesoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(númeroDePropiedad)
                    .addComponent(textoNumPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(textoNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantums))
                .addGap(38, 38, 38))
        );

        botonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior_boton.png"))); // NOI18N
        botonAnterior.setToolTipText("Muestra el proceso anterior");
        botonAnterior.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente-boton.png"))); // NOI18N
        botonSiguiente.setToolTipText("Muestra el siguiente proceso");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(ingresePrioridad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(prioridad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priori, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(botonAcep, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSiguiente)
                .addGap(37, 37, 37))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresePrioridad)
                    .addComponent(textoPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(botonAcep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prioridad)
                            .addComponent(priori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAnterior))
                    .addComponent(botonSiguiente))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRegresarActionPerformed
    {//GEN-HEADEREND:event_botonRegresarActionPerformed
        Archivos.guarda(this, MenuPrincipal.lista, "Datos.dat");
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSalirActionPerformed
    {//GEN-HEADEREND:event_botonSalirActionPerformed
        Archivos.guarda(this, MenuPrincipal.lista, "Datos.dat");
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        MenuPrincipal.lista = (LDLC) Archivos.carga(this, "Datos.dat");
        if (MenuPrincipal.lista == null || MenuPrincipal.lista.getR() == null)
        {
            Mensajes.error(this, "No hay datos para mostrar. Lista vacía.");
            new MenuPrincipal().setVisible(true);
            dispose();
        }
        botonAnterior.setEnabled(false);
        botonSiguiente.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void textoPrioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textoPrioActionPerformed
    {//GEN-HEADEREND:event_textoPrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPrioActionPerformed

    private void textoPrioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoPrioKeyPressed
    {//GEN-HEADEREND:event_textoPrioKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, textoPrio, botonAcep);
    }//GEN-LAST:event_textoPrioKeyPressed

    private void textoPrioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoPrioKeyTyped
    {//GEN-HEADEREND:event_textoPrioKeyTyped
        Validaciones.validaEntero(evt, 2, String.valueOf(textoPrio.getText()));
    }//GEN-LAST:event_textoPrioKeyTyped

    private void botonAcepActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAcepActionPerformed
    {//GEN-HEADEREND:event_botonAcepActionPerformed
        try
        {
            MenuPrincipal.lista = (LDLC) Archivos.carga(this, "Datos.dat");
            NodoL aux2 = MenuPrincipal.lista.getR();
            aux = null;
            do
            {
                aux2 = aux2.getSiguiente();
                if (((Prioridad) aux2.getObj()).getNoPrioridad() == Integer.valueOf(textoPrio.getText()))
                {
                    aux = aux2;
                }
            } while (aux2 != MenuPrincipal.lista.getR());

            if (aux != null)
            {
                aux3 = ((Prioridad) aux.getObj()).getCola().getAtras().getSiguiente();
                priori.setText(String.valueOf(((Prioridad) aux.getObj()).getNoPrioridad()));
                textoNumPrioridad.setText(String.valueOf(((Prioridad) aux.getObj()).getNoPrioridad()));
                textoNom.setText(((Proceso) aux3.getObj()).getNombre());
                textoQuan.setText(String.valueOf(((Proceso) aux3.getObj()).getQuantums()));
                if (aux3 == ((Prioridad) aux.getObj()).getCola().getAtras())
                {
                    botonSiguiente.setEnabled(false);
                } else
                {
                    botonSiguiente.setEnabled(true);
                }
                botonAnterior.setEnabled(false);
            } else
            {
                Mensajes.error(this, "No se encontró la prioridad.");
                CtrlInterfaz.limpia(textoPrio, textoNom, textoNumPrioridad, textoQuan, priori);
                CtrlInterfaz.cambia(textoPrio);
                botonAnterior.setEnabled(false);
                botonSiguiente.setEnabled(false);
            }
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
            new MenuPrincipal().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_botonAcepActionPerformed

    private void textoNumPrioridadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoNumPrioridadKeyTyped
    {//GEN-HEADEREND:event_textoNumPrioridadKeyTyped

    }//GEN-LAST:event_textoNumPrioridadKeyTyped

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSiguienteActionPerformed
    {//GEN-HEADEREND:event_botonSiguienteActionPerformed
        try
        {
            MenuPrincipal.lista = (LDLC) Archivos.carga(this, "Datos.dat");
            ColasCircularesDinamicas colaAux = new ColasCircularesDinamicas();
            Nodo nodo = aux3.getSiguiente();
            do
            {
                aux3 = ((Prioridad) aux.getObj()).getCola().getAtras().getSiguiente();
                if (nodo == aux3.getSiguiente())
                {
                    textoNumPrioridad.setText(String.valueOf(((Proceso) nodo.getObj()).getNoPrioridad()));
                    textoNom.setText(((Proceso) nodo.getObj()).getNombre());
                    textoQuan.setText(String.valueOf(((Proceso) nodo.getObj()).getQuantums()));
                }
                colaAux.inserta(((Prioridad) aux.getObj()).getCola().elimina());
            } while (((Prioridad) aux.getObj()).getCola().getAtras() != null);
            ((Prioridad) aux.getObj()).setCola(colaAux);

            aux3 = nodo;

            if (aux3 == ((Prioridad) aux.getObj()).getCola().getAtras())
            {
                botonSiguiente.setEnabled(false);
            }
            botonAnterior.setEnabled(true);
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
        }
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonAcepKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_botonAcepKeyPressed
    {//GEN-HEADEREND:event_botonAcepKeyPressed
        try
        {
            MenuPrincipal.lista = (LDLC) Archivos.carga(this, "Datos.dat");
            NodoL aux2 = MenuPrincipal.lista.getR();
            aux = null;
            do
            {
                aux2 = aux2.getSiguiente();
                if (((Prioridad) aux2.getObj()).getNoPrioridad() == Integer.valueOf(textoPrio.getText()))
                {
                    aux = aux2;
                }
            } while (aux2 != MenuPrincipal.lista.getR());

            if (aux != null)
            {
                aux3 = ((Prioridad) aux.getObj()).getCola().getAtras().getSiguiente();
                priori.setText(String.valueOf(((Prioridad) aux.getObj()).getNoPrioridad()));
                textoNumPrioridad.setText(String.valueOf(((Prioridad) aux.getObj()).getNoPrioridad()));
                textoNom.setText(((Proceso) aux3.getObj()).getNombre());
                textoQuan.setText(String.valueOf(((Proceso) aux3.getObj()).getQuantums()));
                if (aux3 == ((Prioridad) aux.getObj()).getCola().getAtras())
                {
                    botonSiguiente.setEnabled(false);
                } else
                {
                    botonSiguiente.setEnabled(true);
                }
                botonAnterior.setEnabled(false);
            } else
            {
                Mensajes.error(this, "No se encontró la prioridad.");
                CtrlInterfaz.limpia(textoPrio, textoNom, textoNumPrioridad, textoQuan, priori);
                CtrlInterfaz.cambia(textoPrio);
                botonAnterior.setEnabled(false);
                botonSiguiente.setEnabled(false);
            }
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
            new MenuPrincipal().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_botonAcepKeyPressed

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAnteriorActionPerformed
    {//GEN-HEADEREND:event_botonAnteriorActionPerformed
        try
        {
            MenuPrincipal.lista = (LDLC) Archivos.carga(this, "Datos.dat");
            ColasCircularesDinamicas colaAux = new ColasCircularesDinamicas();
            Nodo nodo = null;
            do
            {
                nodo = ((Prioridad) aux.getObj()).getCola().getAtras().getSiguiente();
                if (nodo.getSiguiente() == aux3)
                {
                    textoNumPrioridad.setText(String.valueOf(((Proceso) nodo.getObj()).getNoPrioridad()));
                    textoNom.setText(((Proceso) nodo.getObj()).getNombre());
                    textoQuan.setText(String.valueOf(((Proceso) nodo.getObj()).getQuantums()));
                    aux3 = nodo;
                }
                colaAux.inserta(((Prioridad) aux.getObj()).getCola().elimina());
            } while (((Prioridad) aux.getObj()).getCola().getAtras() != null);
            ((Prioridad) aux.getObj()).setCola(colaAux);

            if (aux3 == ((Prioridad) aux.getObj()).getCola().getAtras().getSiguiente())
            {
                botonAnterior.setEnabled(false);
            }
            botonSiguiente.setEnabled(true);
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
        }
    }//GEN-LAST:event_botonAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ConsultasProcesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcep;
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel ingresePrioridad;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel númeroDePropiedad;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelProceso;
    private javax.swing.JTextField priori;
    private javax.swing.JLabel prioridad;
    private javax.swing.JLabel quantums;
    private javax.swing.JTextField textoNom;
    private javax.swing.JTextField textoNumPrioridad;
    private javax.swing.JTextField textoPrio;
    private javax.swing.JTextField textoQuan;
    // End of variables declaration//GEN-END:variables
}
