/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import cjb.ci.Mensajes;
import edd.LDLC;
import edd.Manipulacion;
import poo.Archivos;

/**
 *
 * @author osval
 */
public class MenuPrincipal extends javax.swing.JFrame
{

    public static LDLC lista = new LDLC();
    public static int sema;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonAltaProceso = new javax.swing.JButton();
        botonBajaProceso = new javax.swing.JButton();
        botonProcesar = new javax.swing.JButton();
        botonConsutas = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JLabel();
        imagenProceso = new javax.swing.JLabel();
        botonConsutaPróximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        panel.setBackground(new java.awt.Color(48, 146, 255));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SímboloCerrar.png"))); // NOI18N
        botonSalir.setToolTipText("Cerrar programa");
        botonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonSalirActionPerformed(evt);
            }
        });

        botonAltaProceso.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonAltaProceso.setText("Alta de proceso");
        botonAltaProceso.setToolTipText("Crea un nuevo proceso");
        botonAltaProceso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonAltaProceso.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonAltaProcesoActionPerformed(evt);
            }
        });

        botonBajaProceso.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonBajaProceso.setText("Baja de proceso");
        botonBajaProceso.setToolTipText("Elimina un proceso por nombre");
        botonBajaProceso.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonBajaProcesoActionPerformed(evt);
            }
        });

        botonProcesar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonProcesar.setText("Procesar");
        botonProcesar.setToolTipText("Procesa el siguiente elemento");
        botonProcesar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonProcesarActionPerformed(evt);
            }
        });

        botonConsutas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonConsutas.setText("Consulta de procesos");
        botonConsutas.setToolTipText("Muestra procesos por prioridad");
        botonConsutas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonConsutasActionPerformed(evt);
            }
        });

        menuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        menuPrincipal.setText("Menú Principal");

        imagenProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proceso (1).png"))); // NOI18N

        botonConsutaPróximo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonConsutaPróximo.setText("Consulta Próximo");
        botonConsutaPróximo.setToolTipText("Muestra procesos por prioridad");
        botonConsutaPróximo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonConsutaPróximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPrincipal)
                    .addComponent(imagenProceso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonAltaProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBajaProceso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonProcesar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonConsutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonConsutaPróximo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenProceso))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(botonAltaProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(botonBajaProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(botonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botonConsutas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botonConsutaPróximo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSalirActionPerformed
    {//GEN-HEADEREND:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonConsutasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonConsutasActionPerformed
    {//GEN-HEADEREND:event_botonConsutasActionPerformed
        new ConsultasProcesos().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonConsutasActionPerformed

    private void botonAltaProcesoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAltaProcesoActionPerformed
    {//GEN-HEADEREND:event_botonAltaProcesoActionPerformed
        new AltasDeProcesos().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonAltaProcesoActionPerformed

    private void botonBajaProcesoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBajaProcesoActionPerformed
    {//GEN-HEADEREND:event_botonBajaProcesoActionPerformed
        new BajasDeProcesos().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonBajaProcesoActionPerformed

    private void botonProcesarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonProcesarActionPerformed
    {//GEN-HEADEREND:event_botonProcesarActionPerformed
        try
        {
            if (lista.getR() == null)
            {
                Mensajes.error(this, "Lista vacía");
                sema = 0;
            } else
            {
                lista = Manipulacion.procesar(lista);
                Mensajes.exito(this, "Se procesó el siguiente elemento");
                Archivos.guarda(this, lista, "Datos.dat");
                sema = 1;
            }
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.getMessage());
        }

    }//GEN-LAST:event_botonProcesarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        MenuPrincipal.setDefaultLookAndFeelDecorated(false);
        try
        {
            lista = (LDLC) Archivos.carga(this, "Datos.dat");

        } catch (Exception e)
        {
            if (lista == null)
            {
                Mensajes.error(this, "No se encotraron los datos");
            } else
            {
                Mensajes.error(this, "Error..." + e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Archivos.guarda(this, lista, "Datos.dat");
    }//GEN-LAST:event_formWindowClosing

    private void botonConsutaPróximoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonConsutaPróximoActionPerformed
    {//GEN-HEADEREND:event_botonConsutaPróximoActionPerformed
        if (sema == 1)
        {
            new ConsultaPróximo().setVisible(true);
            dispose();
        }else
        {
            Mensajes.error(this, "No se ha procesado ningun elemento.");
        }

    }//GEN-LAST:event_botonConsutaPróximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAltaProceso;
    private javax.swing.JButton botonBajaProceso;
    private javax.swing.JButton botonConsutaPróximo;
    private javax.swing.JButton botonConsutas;
    private javax.swing.JButton botonProcesar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel imagenProceso;
    private javax.swing.JLabel menuPrincipal;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

}
