
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 30 09:11:14 CDT 2024
//----------------------------------------------------

package principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Signo_Corchete_Cerrado = 30;
  public static final int End = 3;
  public static final int Signo_Menor = 35;
  public static final int If = 10;
  public static final int Signo_Llave_Abierta = 19;
  public static final int Signo_Mayor = 33;
  public static final int Sub = 8;
  public static final int Signo_Grado = 34;
  public static final int Signo_Comillas = 51;
  public static final int Signo_doblepunto = 28;
  public static final int Else = 26;
  public static final int Signo_Exclamacion_Invertida = 29;
  public static final int Signo_Exclamacion = 41;
  public static final int Signo_Porcentaje = 36;
  public static final int Signo_Potencia = 31;
  public static final int Console = 47;
  public static final int While = 11;
  public static final int Op_AND = 37;
  public static final int Division = 16;
  public static final int Int = 9;
  public static final int ReadLine = 50;
  public static final int Signo_Dolar = 42;
  public static final int Signo_Guion_Bajo = 43;
  public static final int Signo_Corchete_Abierto = 27;
  public static final int Signo_punto = 24;
  public static final int EOF = 0;
  public static final int Signo_Numeral = 25;
  public static final int Signo_Interrogacion = 32;
  public static final int error = 1;
  public static final int WriteLine = 48;
  public static final int Module = 7;
  public static final int Integer = 40;
  public static final int As = 4;
  public static final int Linea = 2;
  public static final int Signo_Parentesis_Cerrado = 18;
  public static final int ERROR = 46;
  public static final int Op_OR = 44;
  public static final int Dim = 6;
  public static final int String = 5;
  public static final int Signo_Llave_Cerrada = 20;
  public static final int Identificador = 23;
  public static final int Resta = 14;
  public static final int Signo_puntoycoma = 22;
  public static final int Multiplicacion = 15;
  public static final int ReadKey = 49;
  public static final int Numero = 45;
  public static final int Suma = 13;
  public static final int Signo_Interrogacion_Invertida = 39;
  public static final int Main = 21;
  public static final int Signo_Apostrofe = 38;
  public static final int Igual = 12;
  public static final int Signo_Parentesis_Abierto = 17;
}

