/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import cjb.ci.Mensaje;
import com.formdev.flatlaf.FlatDarculaLaf;
import javax.swing.UIManager;

/**
 *
 * @author USUARIO
 */
public class SelectReportesComboB extends javax.swing.JFrame
{
    RepAlergAlum v1 = new RepAlergAlum();
    RepAlergAlumH v2 = new RepAlergAlumH();
    RepAlergAlumM v3 = new RepAlergAlumM();
    RepAlergPers v4 = new RepAlergPers();
    RepAlergPersH v5 = new RepAlergPersH();
    RepAlergPersM v6 = new RepAlergPersM();
    RepAlum v7 = new RepAlum();
    RepAlumHom v8 = new RepAlumHom();
    RepAlumMuj v9 = new RepAlumMuj();
    RepDesnAlum v10 = new RepDesnAlum();
    RepDesnAlumH v11 = new RepDesnAlumH();
    RepDesnAlumM v12 = new RepDesnAlumM();
    RepDesnPers v13 = new RepDesnPers();
    RepDesnPersH v14 = new RepDesnPersH();
    RepDesnPersM v15 = new RepDesnPersM();
    RepDiabAlum v16 = new RepDiabAlum();
    RepDiabAlumH v17 = new RepDiabAlumH();
    RepDiabAlumM v18 = new RepDiabAlumM();
    RepDiabPers v19 = new RepDiabPers();
    RepDiabPersH v20 = new RepDiabPersH();
    RepDiabPersM v21 = new RepDiabPersM();
    RepMnrFrecAlum v22 = new RepMnrFrecAlum();
    RepMnrFrecAlumH v23 = new RepMnrFrecAlumH();
    RepMnrFrecAlumM v24 = new RepMnrFrecAlumM();
    RepMnrFrecPers v25 = new RepMnrFrecPers();
    RepMnrFrecPersH v26 = new RepMnrFrecPersH();
    RepMnrFrecPersM v27 = new RepMnrFrecPersM();
    RepMyrFrecAlum v28 = new RepMyrFrecAlum();
    RepMyrFrecAlumH v29 = new RepMyrFrecAlumH();
    RepMyrFrecAlumM v30 = new RepMyrFrecAlumM();
    RepMyrFrecPers v31 = new RepMyrFrecPers();
    RepMyrFrecPersH v32 = new RepMyrFrecPersH();
    RepMyrFrecPersM v33 = new RepMyrFrecPersM();
    RepObsdAlum v34 = new RepObsdAlum();
    RepObsdAlumH v35 = new RepObsdAlumH();
    RepObsdAlumM v36 = new RepObsdAlumM();
    RepObsdPers v37 = new RepObsdPers();
    RepObsdPersH v38 = new RepObsdPersH();
    RepObsdPersM v39 = new RepObsdPersM();
    RepOtrosAlum v40 = new RepOtrosAlum();
    RepOtrosAlumH v41 = new RepOtrosAlumH();
    RepOtrosAlumM v42 = new RepOtrosAlumM();
    RepOtrosPers v43 = new RepOtrosPers();
    RepOtrosPersH v44 = new RepOtrosPersH();
    RepOtrosPersM v45 = new RepOtrosPersM();
    RepPers v46 = new RepPers();
    RepPersHom v47 = new RepPersHom();
    RepPersMuj v48 = new RepPersMuj();
    RepSbpsAlum v49 = new RepSbpsAlum();
    RepSbpsAlumH v50 = new RepSbpsAlumH();
    RepSbpsAlumM v51 = new RepSbpsAlumM();
    RepSbpsPers v52 = new RepSbpsPers();
    RepSbpsPersH v53 = new RepSbpsPersH();
    RepSbpsPersM v54 = new RepSbpsPersM();

    /**
     * Creates new form SelectReportesComboB
     */
    public SelectReportesComboB()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        categoria = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        sexo = new javax.swing.JComboBox<>();
        padecimiento = new javax.swing.JComboBox<>();
        buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selección de Reportes");
        setLocation(new java.awt.Point(200, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumnos", "Personal" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Reportes");

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo/img/regresar-light.png"))); // NOI18N
        regresar.setToolTipText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel11)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Hombres", "Mujeres" }));

        padecimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Alergias", "Desnutrición", "Diabetes", "Obesidad", "Sobrepeso", "Otros Padecimientos", "Mayor Frecuencia", "Menor Frecuencia" }));

        buscar.setBackground(new java.awt.Color(78, 141, 177));
        buscar.setForeground(new java.awt.Color(204, 204, 204));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sector");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sexo");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tipo de Reporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(padecimiento, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(padecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarActionPerformed
    {//GEN-HEADEREND:event_buscarActionPerformed
        if (categoria.getSelectedIndex() == 0)
        {
            // ALUMNOS
            switch (sexo.getSelectedIndex())
            {
                case 0:
                    // GENERALES
                    switch (padecimiento.getSelectedIndex())
                    {
                        // GENERALES
                        case 0:
                            v7.setVisible(true);
                            v7.setLocation(550, 100);
                            break;
                        case 1:
                            v1.setVisible(true);
                            v1.setLocation(550, 100);
                            break;
                        case 2:
                            v10.setVisible(true);
                            v10.setLocation(550, 100);
                            break;
                        case 3:
                            v16.setVisible(true);
                            v16.setLocation(550, 100);
                            break;
                        case 4:
                            v34.setVisible(true);
                            v34.setLocation(550, 100);
                            break;
                        case 5:
                            v49.setVisible(true);
                            v49.setLocation(550, 100);
                            break;
                        case 6:
                            v40.setVisible(true);
                            v40.setLocation(550, 100);
                            break;
                        case 7:
                            v28.setVisible(true);
                            v28.setLocation(550, 100);
                            break;
                        case 8:
                            v22.setVisible(true);
                            v22.setLocation(550, 100);
                            break;
                    }
                    break;
                case 1:
                    switch (padecimiento.getSelectedIndex())
                    {
                        // ALUMNOS HOMBRES
                        case 0:
                            v8.setVisible(true);
                            v8.setLocation(550, 100);
                            break;
                        case 1:
                            v2.setVisible(true);
                            v2.setLocation(550, 100);
                            break;
                        case 2:
                            v11.setVisible(true);
                            v11.setLocation(550, 100);
                            break;
                        case 3:
                            v17.setVisible(true);
                            v17.setLocation(550, 100);
                            break;
                        case 4:
                            v35.setVisible(true);
                            v35.setLocation(550, 100);
                            break;
                        case 5:
                            v50.setVisible(true);
                            v50.setLocation(550, 100);
                            break;
                        case 6:
                            v41.setVisible(true);
                            v41.setLocation(550, 100);
                            break;
                        case 7:
                            v29.setVisible(true);
                            v29.setLocation(550, 100);
                            break;
                        case 8:
                            v23.setVisible(true);
                            v23.setLocation(550, 100);
                            break;
                    }
                    break;
                case 2:
                    switch (padecimiento.getSelectedIndex())
                    {
                        // ALUMNOS MUJERES
                        case 0:
                            v9.setVisible(true);
                            v9.setLocation(550, 100);
                            break;
                        case 1:
                            v3.setVisible(true);
                            v3.setLocation(550, 100);
                            break;
                        case 2:
                            v12.setVisible(true);
                            v12.setLocation(550, 100);
                            break;
                        case 3:
                            v18.setVisible(true);
                            v18.setLocation(550, 100);
                            break;
                        case 4:
                            v36.setVisible(true);
                            v36.setLocation(550, 100);
                            break;
                        case 5:
                            v51.setVisible(true);
                            v51.setLocation(550, 100);
                            break;
                        case 6:
                            v42.setVisible(true);
                            v42.setLocation(550, 100);
                            break;
                        case 7:
                            v30.setVisible(true);
                            v30.setLocation(550, 100);
                            break;
                        case 8:
                            v24.setVisible(true);
                            v24.setLocation(550, 100);
                            break;
                    }
                    break;
                default:
                    break;
            }
        } else if (categoria.getSelectedIndex() == 1)
        {
            // PERSONAL
            switch (sexo.getSelectedIndex())
            {
                case 0:
                    // GENERALES
                    switch (padecimiento.getSelectedIndex())
                    {
                        // GENERALES
                        case 0:
                            v46.setVisible(true);
                            v46.setLocation(550, 100);
                            break;
                        case 1:
                            v4.setVisible(true);
                            v4.setLocation(550, 100);
                            break;
                        case 2:
                            v13.setVisible(true);
                            v13.setLocation(550, 100);
                            break;
                        case 3:
                            v19.setVisible(true);
                            v19.setLocation(550, 100);
                            break;
                        case 4:
                            v37.setVisible(true);
                            v37.setLocation(550, 100);
                            break;
                        case 5:
                            v52.setVisible(true);
                            v52.setLocation(550, 100);
                            break;
                        case 6:
                            v43.setVisible(true);
                            v43.setLocation(550, 100);
                            break;
                        case 7:
                            v31.setVisible(true);
                            v31.setLocation(550, 100);
                            break;
                        case 8:
                            v25.setVisible(true);
                            v25.setLocation(550, 100);
                            break;
                    }
                    break;
                case 1:
                    switch (padecimiento.getSelectedIndex())
                    {
                        // PERSONAL HOMBRES
                        case 0:
                            v47.setVisible(true);
                            v47.setLocation(550, 100);
                            break;
                        case 1:
                            v5.setVisible(true);
                            v5.setLocation(550, 100);
                            break;
                        case 2:
                            v14.setVisible(true);
                            v14.setLocation(550, 100);
                            break;
                        case 3:
                            v20.setVisible(true);
                            v20.setLocation(550, 100);
                            break;
                        case 4:
                            v38.setVisible(true);
                            v38.setLocation(550, 100);
                            break;
                        case 5:
                            v53.setVisible(true);
                            v53.setLocation(550, 100);
                            break;
                        case 6:
                            v44.setVisible(true);
                            v44.setLocation(550, 100);
                            break;
                        case 7:
                            v32.setVisible(true);
                            v32.setLocation(550, 100);
                            break;
                        case 8:
                            v26.setVisible(true);
                            v26.setLocation(550, 100);
                            break;
                    }
                    break;
                case 2:
                    switch (padecimiento.getSelectedIndex())
                    {
                        // PERSONAL MUJERES
                        case 0:
                            v48.setVisible(true);
                            v48.setLocation(550, 100);
                            break;
                        case 1:
                            v6.setVisible(true);
                            v6.setLocation(550, 100);
                            break;
                        case 2:
                            v15.setVisible(true);
                            v15.setLocation(550, 100);
                            break;
                        case 3:
                            v21.setVisible(true);
                            v21.setLocation(550, 100);
                            break;
                        case 4:
                            v39.setVisible(true);
                            v39.setLocation(550, 100);
                            break;
                        case 5:
                            v54.setVisible(true);
                            v54.setLocation(550, 100);
                            break;
                        case 6:
                            v45.setVisible(true);
                            v45.setLocation(550, 100);
                            break;
                        case 7:
                            v33.setVisible(true);
                            v33.setLocation(550, 100);
                            break;
                        case 8:
                            v27.setVisible(true);
                            v27.setLocation(550, 100);
                            break;
                    }
                    break;
                default:
                    break;
            }
        }

        setLocation(150, 250);
    }//GEN-LAST:event_buscarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_regresarActionPerformed
    {//GEN-HEADEREND:event_regresarActionPerformed
        v1.dispose();
        v2.dispose();
        v3.dispose();
        v4.dispose();
        v5.dispose();
        v6.dispose();
        v7.dispose();
        v8.dispose();
        v9.dispose();
        v10.dispose();
        v11.dispose();
        v12.dispose();
        v13.dispose();
        v14.dispose();
        v15.dispose();
        v16.dispose();
        v17.dispose();
        v18.dispose();
        v19.dispose();
        v20.dispose();
        v21.dispose();
        v22.dispose();
        v23.dispose();
        v24.dispose();
        v25.dispose();
        v26.dispose();
        v27.dispose();
        v28.dispose();
        v29.dispose();
        v30.dispose();
        v31.dispose();
        v32.dispose();
        v33.dispose();
        v34.dispose();
        v35.dispose();
        v36.dispose();
        v37.dispose();
        v38.dispose();
        v39.dispose();
        v40.dispose();
        v41.dispose();
        v42.dispose();
        v43.dispose();
        v44.dispose();
        v45.dispose();
        v46.dispose();
        v47.dispose();
        v48.dispose();
        v49.dispose();
        v50.dispose();
        v51.dispose();
        v52.dispose();
        v53.dispose();
        v54.dispose();
        

        new SelectOption().setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        regresarActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        if (SelectRegistro.datos == null)
        {
            Mensaje.error(this, "No hay registros");
            new SelectOption().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch (Exception ex)
        {
            System.err.println("Failed to initialize LaF");
        }

        UIManager.put("TextComponent.arc", 15);
        UIManager.put("Button.arc", 35);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SelectReportesComboB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> padecimiento;
    private javax.swing.JButton regresar;
    private javax.swing.JComboBox<String> sexo;
    // End of variables declaration//GEN-END:variables
}
